### ISSUE TITLE
Pip installation context maybe broken

### ISSUE THREAD

**Issue by uee9** [flu-crew/parnas#4]
Hello! 

Thanks for a great tool. I have found many uses for it in my work so far. Installation via pip might be broken, however. 

Running this inside a docker container I am working on:
`RUN python3 -m pip install parnas --break-system-packages` 

Produces the following error:

```
1.066 Collecting parnas
1.419   Downloading parnas-0.1.5-py3-none-any.whl.metadata (15 kB)
1.783 Collecting numpy<=1.24,>=1.17 (from parnas)
1.809   Downloading numpy-1.24.0.tar.gz (10.9 MB)
2.358      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 23.0 MB/s eta 0:00:00
3.198   Installing build dependencies: started
6.430   Installing build dependencies: finished with status 'done'
6.433   Getting requirements to build wheel: started
6.531   Getting requirements to build wheel: finished with status 'error'
6.536   error: subprocess-exited-with-error
6.536
6.536   × Getting requirements to build wheel did not run successfully.
6.536   │ exit code: 1
6.536   ╰─> [33 lines of output]
6.536       Traceback (most recent call last):
6.536         File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
6.536           main()
6.536         File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
6.536           json_out['return_val'] = hook(**hook_input['kwargs'])
6.536                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6.536         File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
6.536           backend = _build_backend()
6.536                     ^^^^^^^^^^^^^^^^
6.536         File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
6.536           obj = import_module(mod_path)
6.536                 ^^^^^^^^^^^^^^^^^^^^^^^
6.536         File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
6.536           return _bootstrap._gcd_import(name[level:], package, level)
6.536                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6.536         File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
6.536         File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
6.536         File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
6.536         File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
6.536         File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
6.536         File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
6.536         File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
6.536         File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
6.536         File "<frozen importlib._bootstrap_external>", line 995, in exec_module
6.536         File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
6.536         File "/tmp/pip-build-env-w3endw77/overlay/local/lib/python3.12/dist-packages/setuptools/__init__.py", line 16, in <module>
6.536           import setuptools.version
6.536         File "/tmp/pip-build-env-w3endw77/overlay/local/lib/python3.12/dist-packages/setuptools/version.py", line 1, in <module>
6.536           import pkg_resources
6.536         File "/tmp/pip-build-env-w3endw77/overlay/local/lib/python3.12/dist-packages/pkg_resources/__init__.py", line 2172, in <module>
6.536           register_finder(pkgutil.ImpImporter, find_on_path)
6.536                           ^^^^^^^^^^^^^^^^^^^
6.536       AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
6.536       [end of output]
6.536
6.536   note: This error originates from a subprocess, and is likely not a problem with pip.
6.538 error: subprocess-exited-with-error
6.538
6.538 × Getting requirements to build wheel did not run successfully.
6.538 │ exit code: 1
6.538 ╰─> See above for output.
6.538
6.538 note: This error originates from a subprocess, and is likely not a problem with pip.
------
```
I do previously install `nextstrain-augur` via `pip` into the container. Both have many shared dependencies so this might be a cause of the issue. 

Many thanks, 
Matt

**Comment by tkanderson** [comment]
Thank you @uee9 it could be a numpy/python3.12 issue. short term, in your local setup.py, can you specify numpy==1.26.4 and see if that works? @markin-alex  can jump in and correct me too.

**Comment by markin-alex** [comment]
Hi Matt @uee9, thanks for using the tool and bringing this issue to our attention!
I've removed the upper bound on numpy from setup.py. Hopefully, that resolves it.

I haven't pushed the update to PyPi yet,  but can you please try and install the latest GitHub version to see if its solved?

Thanks!
-Alexey

**Comment by uee9** [comment]
Hi @markin-alex, 

Yes I was able to successfully build the package with this update. Thanks for the quick solution!

Matt

**Comment by markin-alex** [comment]
Brilliant, thanks!
